### ISSUE TITLE
[Feature Request] Change of two attribute field names in investigation.xlsx and study.xlsx

### ISSUE THREAD

**Issue by Hannah-Doerpholz** [nfdi4plants/arcCommander#161] opened 2022-11-29 08:55 UTC
**Is your feature request related to a problem? Please describe.**
In the investigation and study file there are two publication fields: "Investigation Publication PubMed ID" and "Study Publication PubMed ID". According to the ISA-tab specification (which to my knowledge is what the xlsx files are based on) it should only be "Investigation PubMed ID" and "Study PubMed ID".

**Describe the solution you'd like**
Both names should be changed to the official terms.

**Comment by HLWeil** [comment] 2022-11-29 11:54
Hey, thanks for the heads-up. This is a duplicate of #107 though, so will close this here.

**Closed by HLWeil** 2022-11-29 11:54 UTC
